#!/bin/bash
LABEL=9adad6e-dirty
LABEL=iccad18
XDEVICE=adm-pcie-ku3

run() {
    #for num_tile in $(seq 100 100 800)
    for num_tile in 128 256 512 1024
    do
        for t in $(DRAM_BANK=2 with-sdaccel bin/${LABEL}/${XDEVICE}/${app}-tile${tile_size}-iterate${iterate}-border-ignored bit/${LABEL}/${XDEVICE}/${app}-hw-tile${tile_size}-unroll${unroll}-2ddr-${separate}iterate${iterate}-border-ignored-none-clustered.xclbin ${tile_size//x/ } ${num_tile}|&grep 'Kernel execution time:'|awk '{print $4}')
        do
            echo -n "$t "
        done
    done
}

app=denoise3d
tile_size=128x128
iterate=1
unroll=8
separate=separated-
export DRAM_SEPARATE=yes
run
