#!/bin/bash
LABEL=9adad6e-dirty
LABEL=iccad18
XDEVICE=adm-pcie-ku3
separate=separated-
export DRAM_SEPARATE=yes
bank=2

run() {
    #run_freq
    #run_estimate
    #run_post_syn_util
    run_exec_time
}

. ./test-funcs.sh
#. ./test-funcs-rep.sh

app=sobel2d
iterate=1
unroll=32
for tile_size in 4096 8192 16384 32768 65536
do
    run
done

app=denoise2d
iterate=1
unroll=8
for tile_size in 4096 8192 16384 32768 65536
do
    run
done

app=denoise3d
iterate=1
unroll=8
for tile_size in 32x32 64x64 128x128 256x256 512x512
do
    run
done

for app in jacobi2d seidel2d
do
    iterate=1
    unroll=16
    for tile_size in 4096 8192 16384 32768 65536
    do
        run
    done
done

for app in jacobi3d heat3d
do
    iterate=1
    unroll=16
    for tile_size in 32x32 64x64 128x128 256x256 512x512
    do
        run
    done
done

