#!/usr/bin/python3
import json
import sys

from soda.optimization import tcse


def main():
  j = json.load(sys.stdin)
  schedule = tcse.make_schedule_from_json(j, j.get('rattrs'), j.get('aattrs'))
  j["num_ops"] = schedule.cost
  j["total_distance"] = schedule.total_distance
  print(json.dumps(j, indent=2))

if __name__ == '__main__':
  main()
