#!/usr/bin/python3
import json
import sys

from soda.optimization import computation_reuse as cr


def main():
  j = json.load(sys.stdin)
  schedule = cr.make_schedule_from_json(j, j.get('rattrs'), j.get('aattrs'))
  j["num_ops"] = schedule.num_ops
  j["total_distance"] = schedule.total_distance
  print(json.dumps(j, indent=2))


if __name__ == '__main__':
  main()
