#!/usr/bin/python3
import mmap
import os
import sys

offset = 8+32+256+8
for file_name in sys.argv[1:]:
    with open(file_name, "r+b") as f:
        correct_size = os.stat(f.fileno()).st_size
        mm = mmap.mmap(f.fileno(), min(offset+8, correct_size))
        if mm[:8] == 'xclbin2\0'.encode('utf-8'):
            previous_size = int.from_bytes(mm[offset:offset+8], byteorder=sys.byteorder)
            if previous_size != correct_size:
                print('fix %s: %d -> %d' % (file_name, previous_size, correct_size))
                mm[offset:offset+8] = correct_size.to_bytes(8, byteorder=sys.byteorder)
            else:
                print('skip %s: %d correct' % (file_name, correct_size))
        else:
            print('skip %s: not xclbin2 file' % file_name)
        mm.close()
