#!/usr/bin/python3

import logging
import os
import sys

from haoda import util
from haoda.report.xilinx import rtl

logging.basicConfig(level=logging.WARNING,
                    format='%(levelname)s:%(name)s:%(lineno)d: %(message)s')
_logger = logging.getLogger().getChild(os.path.basename(__file__))

if __name__ == '__main__':
  top_name = 'Dataflow'
  if len(sys.argv) > 1:
    top_name = sys.argv[1]
  try:
    with rtl.ReportXoUtil(sys.stdin.buffer, sys.stdout,
                          top_name=top_name) as proc:
      stdout, stderr = proc.communicate()
  except util.InternalError:
    _logger.error(stdout.decode())
    _logger.error(stderr.decode())
  else:
    log_func = _logger.error if proc.returncode != 0 else _logger.debug
    log_func(stdout.decode())
    log_func(stderr.decode())
