name: test-and-publish

on:
  [push, pull_request]

jobs:
  test-and-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install setuptools and wheel
        run: pip install --upgrade setuptools wheel
      - name: Checkout myself
        uses: actions/checkout@v1
      - name: Install myself
        run: python setup.py install
        working-directory: ./src
      - name: Run unit tests
        run: python -m unittest discover --start-directory src
      - name: Build dist
        run: python setup.py sdist bdist_wheel
        working-directory: ./src
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
